#!/usr/bin/env python3
"""Emit the cut-down registry the Hubitat app actually reads.

The canonical registry is written for people and for CI. It carries provenance,
status, source visibility and, since the documentation enrichment landed, whole
paragraphs of scraped prose per entry. That is the right shape for reviewing a
classification and the wrong shape for a hub to download.

It reached 165KB, and the app fetches and parses it inside a single Hubitat
execution. That execution died. Hubitat only commits state at the END of an
execution, so nothing survived: no matches, no error, no trace. The app's own
panel then reported "registry not fetched yet" to a user who had just run a
scan, because never-ran and died-trying looked identical from the outside.

So the app gets its own file containing only the fields it evaluates:

    entry     id, matchMode, matchRules, dependencies
    rule      field, operator, value
    dependency  name, class, runtimeCriticality

Everything else is dropped, along with entries carrying no dependencies, which
cannot contribute a match no matter what they match on.

`name` is kept although the app never reads it. It costs about 2KB across the
whole file and it is the difference between a debuggable diff and a wall of
slugs.

ALL match rules are kept, including the ones the app cannot evaluate. Dropping
those would silently change matchMode=ALL results: an entry requiring a driver
name the app cannot see must stay unevaluable, not become vacuously satisfied.

    python build_slim_registry.py [--check]

--check verifies the committed slim file is current without rewriting it, for
use in CI where a stale artifact should fail the build rather than be quietly
regenerated.
"""

import argparse
import json
import pathlib
import sys

CANONICAL = pathlib.Path('hubitat_automation_map_app_integration_registry.json')
SLIM = pathlib.Path('hubitat_automation_map_app_integration_registry_slim.json')

# The point of this file. If it regrows past this, the app will start failing
# the same silent way again, so fail the build instead and make someone look.
# Sized with room to roughly double the current entry count.
MAX_BYTES = 64_000

RULE_FIELDS = ('field', 'operator', 'value')
DEP_FIELDS = ('name', 'class', 'runtimeCriticality')


def slim_entry(entry):
    deps = []
    for dep in entry.get('dependencies') or []:
        if not isinstance(dep, dict):
            continue
        name = str(dep.get('name') or '').strip()
        if not name or name == 'None':
            continue
        deps.append({k: dep.get(k) for k in DEP_FIELDS})
    if not deps:
        return None

    rules = []
    for rule in entry.get('matchRules') or []:
        if isinstance(rule, dict):
            rules.append({k: rule.get(k) for k in RULE_FIELDS})
    if not rules:
        return None

    return {
        'id': entry.get('id'),
        'name': entry.get('name'),
        'matchMode': entry.get('matchMode') or 'ANY',
        'matchRules': rules,
        'dependencies': deps,
    }


def build():
    canonical = json.loads(CANONICAL.read_text('utf-8'))
    entries = []
    for entry in canonical.get('entries') or []:
        if isinstance(entry, dict):
            slim = slim_entry(entry)
            if slim:
                entries.append(slim)
    entries.sort(key=lambda e: str(e.get('id') or ''))

    doc = {
        'schemaVersion': canonical.get('schemaVersion'),
        'registryName': canonical.get('registryName'),
        'generatedDate': canonical.get('generatedDate'),
        'generatedFrom': CANONICAL.name,
        'note': ('Generated by build_slim_registry.py. Do not edit. Edit the canonical '
                 'registry instead. This file exists because the Hubitat app must fetch '
                 'and parse it inside one execution.'),
        'entries': entries,
    }
    # Separators matter here: the default ", " / ": " costs about 8% on a file
    # whose entire reason for existing is size.
    return json.dumps(doc, indent=1, ensure_ascii=False, separators=(',', ':')) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='fail if the committed file is stale, instead of rewriting it')
    args = ap.parse_args()

    text = build()
    size = len(text.encode('utf-8'))
    count = len(json.loads(text)['entries'])
    dropped = len(json.loads(CANONICAL.read_text('utf-8')).get('entries') or []) - count

    if size > MAX_BYTES:
        print(f'FAIL: slim registry is {size} bytes, over the {MAX_BYTES} limit.', file=sys.stderr)
        print('The app fetches this in one execution. Trim fields or split the file '
              'rather than raising the limit.', file=sys.stderr)
        return 1

    if args.check:
        if not SLIM.exists():
            print(f'FAIL: {SLIM} is missing. Run build_slim_registry.py.', file=sys.stderr)
            return 1
        if SLIM.read_text('utf-8') != text:
            print(f'FAIL: {SLIM} is stale. Run build_slim_registry.py and commit.', file=sys.stderr)
            return 1
        print(f'{SLIM} is current: {count} entries, {size} bytes.')
        return 0

    SLIM.write_text(text, encoding='utf-8', newline='\n')
    canonical_size = CANONICAL.stat().st_size
    print(f'{SLIM} written: {count} entries, {size} bytes '
          f'({100 - round(size / canonical_size * 100)}% smaller than canonical).')
    print(f'  {dropped} entry(s) dropped for having no usable dependency or match rule.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
